try dividing dirs for better process

diff --git a/.github/workflows/version-diff-advanced.yml b/.github/workflows/version-diff-advanced.yml
--- a/.github/workflows/version-diff-advanced.yml
+++ b/.github/workflows/version-diff-advanced.yml
@@ -1,67 +1,90 @@
-# name: version-diff-advanced
-# on: pull_request
+# # name: version-diff-advanced
+# # on: pull_request
     
-# jobs:
-#   diff:
-#     name: Show diff
-#     runs-on: ubuntu-latest
+# # jobs:
+# #   diff:
+# #     name: Show diff
+# #     runs-on: ubuntu-latest
 
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v2
+# #     steps:
+# #       - name: Checkout
+# #         uses: actions/checkout@v2
 
-#       - name: Diff
-#         id: diff-comment-id
-#         run: |
-#           cd keda/
-#           diff_text=""
-#           if diff_text="$(diff --color -br --unified=0 $(ls|tail -2))" && [ $? -ne 1 ]; then
-#             echo "exit code of diff not 1"
-#             exit 1;
-#           fi;
-#           PREFIX=$'<details>\n\n```diff\n\n'
-#           POSTFIX=$'\n\n```\n\n</details>'
-#           diff_text="${PREFIX}${diff_text}${POSTFIX}"
-#           diff_text="${diff_text//'%'/'%25'}"
-#           diff_text="${diff_text//$'\n'/'%0A'}"
-#           diff_text="${diff_text//$'\r'/'%0D'}"
-#           echo "$diff_text"
-#           echo "::set-output name=body::$diff_text"
+# #       - name: Diff
+# #         id: diff-comment-id
+# #         run: |
+# #           cd keda/
+# #           diff_text=""
+# #           if diff_text="$(diff --color -br --unified=0 $(ls|tail -2))" && [ $? -ne 1 ]; then
+# #             echo "exit code of diff not 1"
+# #             exit 1;
+# #           fi;
+# #           PREFIX=$'<details>\n\n```diff\n\n'
+# #           POSTFIX=$'\n\n```\n\n</details>'
+# #           diff_text="${PREFIX}${diff_text}${POSTFIX}"
+# #           diff_text="${diff_text//'%'/'%25'}"
+# #           diff_text="${diff_text//$'\n'/'%0A'}"
+# #           diff_text="${diff_text//$'\r'/'%0D'}"
+# #           echo "$diff_text"
+# #           echo "::set-output name=body::$diff_text"
 
-#       - name: Create comment
-#         uses: peter-evans/create-or-update-comment@v2
-#         with:
-#           issue-number: ${{ github.event.pull_request.number }}
-#           body: |
-#             tbc advanced
-#             ${{ steps.diff-comment-id.outputs.body }}
-#           reactions: rocket
+# #       - name: Create comment
+# #         uses: peter-evans/create-or-update-comment@v2
+# #         with:
+# #           issue-number: ${{ github.event.pull_request.number }}
+# #           body: |
+# #             tbc advanced
+# #             ${{ steps.diff-comment-id.outputs.body }}
+# #           reactions: rocket
 
-name: git diff
+name: git diff dynamic jobs
 on: pull_request
-    
+
 jobs:
-  diff:
-    name: Show diff
+  setup:
     runs-on: ubuntu-latest
-
+    outputs:
+      dir_old: ${{ steps.setup-id.outputs.dir_old }}
+      dir_new: ${{ steps.setup-id.outputs.dir_new }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: setup for comment diff
-        id: diff-comment-id
+      - id: setup-id
         run: |
-          diff_text=$(git diff main...${GITHUB_REF##*/})
-          echo "$diff_text"
-          echo "::set-output name=body::$diff_text"
+          dirs=$(ls|tail -2)
+          dirs=($dirs)
+          echo ${dirs[0]}
+          echo "TRALALA"
+          echo ${dirs[1]}
+          echo "::set-output name=file_array::$file_array"
 
-      - name: Create comment
-        uses: peter-evans/create-or-update-comment@v2
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body: |
-            git diff of versions?
-            ${{ steps.diff-comment-id.outputs.body }}
-          reactions: rocket
+  # diff:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix: 
+  #       old: github.steps.
+  #       new: ["hola",]
+        
+    # needs: setup
+
+    # name: Show diff
+    # runs-on: ubuntu-latest
+
+    # steps:
+    #   - name: Checkout
+    #     uses: actions/checkout@v2
+
+    #   - name: setup for comment diff
+    #     id: diff-comment-id
+    #     run: |
+    #       diff_text=$(git diff main...${GITHUB_REF##*/})
+    #       echo "$diff_text"
+    #       echo "::set-output name=body::$diff_text"
+
+    #   - name: Create comment
+    #     uses: peter-evans/create-or-update-comment@v2
+    #     with:
+    #       issue-number: ${{ github.event.pull_request.number }}
+    #       body: |
+    #         git diff of versions?
+    #         ${{ steps.diff-comment-id.outputs.body }}
+    #       reactions: rocket
       
